<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="index.aspx.cs" MasterPageFile="ShopMaster.Master" Inherits="Agile16_Komis.src.wwwroot.index" %>

<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
        
        <asp:GridView ID="carsDataGridView" runat="server" AutoGenerateColumns="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
        <Columns>
            <asp:ImageField HeaderText="Zdjęcia">
            </asp:ImageField>
            <asp:TemplateField HeaderText="Model" >
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Marka" />
            <asp:TemplateField HeaderText="Rok produkcji" />
            <asp:TemplateField HeaderText="Typ silnika" />
            <asp:BoundField HeaderText="Pojemność silnika" />
            <asp:BoundField HeaderText="Typ skrzyni biegów" />
            <asp:BoundField HeaderText="Ilość biegów" />
            <asp:BoundField HeaderText="Typ paliwa" />
            <asp:BoundField HeaderText="Podwozie" />
            <asp:BoundField HeaderText="Kolor" />
        </Columns>

    </asp:GridView>
</asp:Content>
        