<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="index.aspx.cs" MasterPageFile="ShopMaster.Master" Inherits="Agile16_Komis.src.wwwroot.index" %>

<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
        
        <asp:GridView ID="carsDataGridView" runat="server" AutoGenerateColumns="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
        

    </asp:GridView>
</asp:Content>
        